# Generated by Django 2.1.4 on 2019-08-22 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='computer_tag',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Please enter alphanumeric characters.')]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='serial_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Please enter alphanumeric characters.')]),
        ),
    ]
