# Generated by Django 2.1.4 on 2019-08-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190822_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='branch_code',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='rc_code',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
