# Generated by Django 2.2.4 on 2019-09-01 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_unitremarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='machine_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='machine_brand', to='inventory.Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='machine_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.MachineType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='monitor_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitor_brand', to='inventory.Brand'),
        ),
    ]
