# Generated by Django 2.1.4 on 2019-08-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190821_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
