# Generated by Django 2.2.4 on 2019-09-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190901_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='actual_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='pm_date_done',
            field=models.DateField(blank=True, null=True),
        ),
    ]
