# Generated by Django 2.1.4 on 2019-08-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190822_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='remarks',
            new_name='description',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
