# Generated by Django 2.2.4 on 2019-08-28 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_auto_20190822_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[inventory.validators.validate_mac_address]),
        ),
        migrations.CreateModel(
            name='PreventiveMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_report_number', models.CharField(max_length=255)),
                ('target_date', models.DateField()),
                ('actual_date', models.DateField()),
                ('pm_date_done', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
