# Generated by Django 2.2.4 on 2019-09-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20190911_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpreventivemaintenance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='preventivemaintenance',
            name='status',
        ),
        migrations.AddField(
            model_name='historicalunit',
            name='status',
            field=models.CharField(choices=[('Covered by MA', 'Covered by MA'), ('Not Covered by MA', 'Not Covered by MA')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('Covered by MA', 'Covered by MA'), ('Not Covered by MA', 'Not Covered by MA')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
