# Generated by Django 2.2.4 on 2019-09-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20190911_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpreventivemaintenance',
            name='service_report_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='service_report_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
