# Generated by Django 2.2.4 on 2019-09-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20190914_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpreventivemaintenance',
            name='pm_type',
            field=models.CharField(choices=[('1st PM', '1st PM'), ('2nd PM', '2nd PM'), ('3rd PM', '3rd PM'), ('4th PM', '4th PM')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='pm_type',
            field=models.CharField(choices=[('1st PM', '1st PM'), ('2nd PM', '2nd PM'), ('3rd PM', '3rd PM'), ('4th PM', '4th PM')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
