# Generated by Django 2.2.4 on 2019-09-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20190920_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preventivemaintenance',
            options={'permissions': [('can_view_pm_list', 'Can view pm list'), ('can_view_units_per_pm', 'Can view units per pm')]},
        ),
    ]
