# Generated by Django 2.2.4 on 2019-09-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20190920_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinetype',
            name='machine_class',
            field=models.CharField(choices=[('CPU', 'CPU'), ('Laptop', 'Laptop'), ('Printer', 'Printer')], max_length=50),
        ),
    ]
