# Generated by Django 2.2.4 on 2019-09-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20190922_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preventivemaintenance',
            options={'permissions': [('can_view_pm_list', 'Can view pm list'), ('can_view_units_per_pm', 'Can view units per pm'), ('can_mark_as_done', 'Can mark as done per pm')]},
        ),
    ]
