# Generated by Django 2.2.4 on 2019-10-10 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0018_auto_20191009_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmunithistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pmunithistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pmhistory_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
