# Generated by Django 2.2.4 on 2019-10-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20191010_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_name']},
        ),
        migrations.AlterModelOptions(
            name='businessunit',
            options={'ordering': ['business_unit_name']},
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelOptions(
            name='hddsize',
            options={'ordering': ['hdd_size_name']},
        ),
        migrations.AlterModelOptions(
            name='machinetype',
            options={'ordering': ['machine_type_name']},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['model_name']},
        ),
        migrations.AlterModelOptions(
            name='officeapplication',
            options={'ordering': ['office_app_name']},
        ),
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'ordering': ['os_name']},
        ),
        migrations.AlterModelOptions(
            name='preventivemaintenance',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_pm_list', 'Can view pm list'), ('can_view_units_per_pm', 'Can view units per pm'), ('can_mark_as_done', 'Can mark as done per pm')]},
        ),
        migrations.AlterModelOptions(
            name='processor',
            options={'ordering': ['processor_name']},
        ),
        migrations.AlterModelOptions(
            name='totalram',
            options={'ordering': ['total_ram_name']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_unit_list', 'Can view unit list'), ('can_soft_delete_unit', 'Can soft delete unit'), ('can_view_unit_history', 'Can view unit history')]},
        ),
    ]
