# Generated by Django 2.2.4 on 2019-11-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='client_code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='used_for',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
