# Generated by Django 2.2.4 on 2019-11-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20191117_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpreventivemaintenance',
            name='assigned_personnel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='assigned_personnel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
