# Generated by Django 2.2.4 on 2019-11-30 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20191126_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preventivemaintenance',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_pm_list', 'Can view pm list'), ('can_view_units_per_pm', 'Can view units per pm'), ('can_mark_as_done', 'Can mark as done per pm'), ('can_soft_delete_pm', 'Can soft delete pm'), ('can_generate_certification_form', 'Can generate certification form'), ('can_generate_excel_report_count', 'Can generate excel report count')]},
        ),
        migrations.AlterField(
            model_name='unit',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_unit', to='inventory.BusinessUnit'),
        ),
    ]
