# Generated by Django 2.2.4 on 2019-11-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20191130_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.BusinessUnit'),
        ),
    ]
