# Generated by Django 2.2.4 on 2019-12-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20191130_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPreventiveMaintenance',
        ),
    ]
