# Generated by Django 2.2.4 on 2019-12-01 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_delete_historicalpreventivemaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmunithistory',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Unit'),
        ),
    ]
