# Generated by Django 2.2.4 on 2019-12-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20191201_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmunithistory',
            name='preventive_maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.PreventiveMaintenance'),
        ),
    ]
