# Generated by Django 2.2.4 on 2019-12-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_auto_20191201_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventivemaintenance',
            name='actual_date',
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='monitor_type',
            field=models.CharField(blank=True, choices=[('LCD', 'LCD'), ('CRT', 'CRT'), ('LED', 'LED')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='monitor_type',
            field=models.CharField(blank=True, choices=[('LCD', 'LCD'), ('CRT', 'CRT'), ('LED', 'LED')], max_length=10, null=True),
        ),
    ]
