# Generated by Django 2.2.4 on 2019-12-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_pmunithistory_pm_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmunithistory',
            name='pm_date_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
