# Generated by Django 2.2.4 on 2019-12-08 17:50

from django.db import migrations, models
import inventory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_pmunithistory_pm_date_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='certification_forms/', validators=[inventory.validators.validate_file_extension]),
        ),
    ]
