# Generated by Django 2.2.4 on 2020-01-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auto_20191208_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preventivemaintenance',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_pm_list', 'Can view pm list'), ('can_view_units_per_pm', 'Can view units per pm'), ('can_mark_as_done', 'Can mark as done per pm'), ('can_soft_delete_pm', 'Can soft delete pm'), ('can_generate_certification_form', 'Can generate certification form'), ('can_generate_pm_attachment', 'Can generate pm attachment'), ('can_generate_excel_report_count', 'Can generate excel report count')]},
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='pm_done',
            field=models.BooleanField(default=False),
        ),
    ]
